### ISSUE TITLE
Unable to pip install supporting library pyppeteer-ghost-cursor.

### ISSUE THREAD

**Issue by mohamedasic** [KimMinKyeom/Hcaptcha-Solver#5]
For some reason not able to pip install supporting library pyppeteer-ghost-cursor and error below for your reference. Kindly let me know if I'm doing something wrong.

Python version 3.10.4
pip version 22.0.4

C:\Users\Administrator>pip install pyppeteer-ghost-cursor
Collecting pyppeteer-ghost-cursor
  Using cached pyppeteer_ghost_cursor-0.2.3-py3-none-any.whl (21 kB)
Collecting bezier
  Using cached bezier-2021.2.12.tar.gz (313 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      The BEZIER_INSTALL_PREFIX environment variable must be set.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by KimMinKyeom** [comment]
Use python_ghost_cursor instead of pyppeteer_ghost_cursor and replace the bezier module file with github.com/dhermes/bezier/tree/main/src/python/bezier
