### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by yuhhere** [KimMinKyeom/Hcaptcha-Solver#7]
Hey, can the developer of this contact me on discord? I'd like some help: DDZZH#7231

**Comment by attack1975** [comment]
Amazing !!!!

**Comment by KimMinKyeom** [comment]
I will contact you after replacing the old module and making additional patches for hcaptcha

**Comment by yuhhere** [comment]
Perfect, any idea when that will be?

**Comment by yuhhere** [comment]
@KimMinKyeom hey update?
